#:kivy 1.0

Main:
    Main:


<Main>:
    name: "main"
    GridLayout: 
        cols:2
        Label:
            text:"Reservatório A: \n" + root.contentA
            id: titleA
        Image:
            id: imageA 
            source: root.imageA
        Label:
            text:"Reservatório B: \n" + root.contentB
            id: titleB
        Image: 
            id: imageB
            source: root.imageB

